# -*- coding: utf-8 -*-
"""
Date: 02/2023
Version: 1.0
Author: (I) Jose Pena
Website: https://github.com/JoseJuan98

Utils
=====

Utils for tests

"""


def message_error_expected(input_value, expected, error_value) -> str:
    """
    Formatted error message for tests

    Args:
        input_value: input value for test
        expected: expected value for the test
        error_value: value generated by the test

    Returns:
        str: message of error
    """
    return f"Failed test with input value {input_value}" f"\nexpected value {expected}," f"\nbut got {error_value}"
